# Generated by Django 3.1.7 on 2021-03-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='soldout',
            new_name='is_soldout',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_categories',
            new_name='sub_category',
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.ManyToManyField(through='product.ProductLabel', to='product.Label'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('content', models.TextField(max_length=3000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
