# Generated by Django 3.1.7 on 2021-03-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210319_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='cagetory',
            new_name='category',
        ),
    ]
